### ISSUE TITLE
The extracted slots from SAVi are changing across time

### ISSUE THREAD

**Issue by HilbertXu** [pairlab/SlotFormer#12]
Hi,

Thanks for your amazing work! 
I tried to train StoSAVi model with the provided script with default settings to extract slots. However, I find that the extracted slots are not stable and changing across time, which leads to a 'blinking' effect in the generated slot videos. Please check the attached gif, which is generated by calling the` _sample_video` function in the `base_slot.method.SAViMethod`. Could you please provide me with some suggestion about why this happend and how to fix this problem?

I would really appreciate your suggestion and thanks in advance :p

Yucheng

![0](https://github.com/user-attachments/assets/22612e52-7417-4d37-bfc6-d21e9d1f47da)
![1](https://github.com/user-attachments/assets/dca32348-bf52-4881-b481-a07cab34e15d)
![2](https://github.com/user-attachments/assets/1261114a-2e00-4e83-9286-058703091fbb)
![3](https://github.com/user-attachments/assets/8b828d85-00ec-40f4-8281-d737606d5ea8)
![4](https://github.com/user-attachments/assets/70ed3e2d-1e93-4020-823f-49d39b84efb3)

**Comment by Wuziyi616** [comment]
Yes, this also happened in my experiments. The training of unsupervised methods like Slot Attention is extremely unstable. I need to run (at least) 5 random seeds to get a stable result. Also, strictly speaking, the current Slot Attention code only supports correct inference of the pre-trained model, i.e., extracting slots from videos. I cannot guarantee its training code can reproduce the results, unfortunately.

Note that this is an issue with the slot model, not our proposed SlotFormer method. I'd recommend you to just use the pre-trained weights for slot extraction. Our SlotFormer part of code should be correct.

**Comment by HilbertXu** [comment]
Hi @Wuziyi616 ,

Thanks for the clarification! I will try the provided pre-trained weights first

Yucheng

**Comment by Wuziyi616** [comment]
Sure. Let me know if you have any issues using it.
