### ISSUE TITLE
Phyre dataloader  triggers the assertion "assert label == self.act_labels[idx]"

### ISSUE THREAD

**Issue by K-lina** [pairlab/SlotFormer#13]
Hello, 
Thanks for your amazing work
I encountered an issue while running the Phyre part of the code which triggered the assertion on **line 150** in slotformer/base_slots/datasets/phyre.py: **"assert label == self.act_labels[idx]"**. I'd like to know if you have come across a similar problem. When this issue arises, should I use the labels from the simulation statuses in the cache_data obtained via **phyre.get_default_100k_cache** or should I use **sim.status** from the simulation results obtained by:

*sim = self.simulator.simulate_action(
    int(task_id),
    acts,
    stride=60 // self.fps,
    need_images=True,
    need_featurized_objects=False,
)*
In the *RPIN*  model, *sim.status is used as the label*, which I am currently using, but it's not yielding good results. Have you encountered similar issues or do you have any suggestions?
I would greatly appreciate your advice. Thank you.

**Comment by Wuziyi616** [comment]
Yes it sometimes does happen, though it's quite random. I think when this happened I just used the cached one.

**Comment by K-lina** [comment]
Thank you for your advice!
