### ISSUE TITLE
DDP settings

### ISSUE THREAD

**Issue by hello-jinwoo** [pairlab/SlotFormer#5]
Hi there, 

during implementing your great research code, I faced a problem that the DDP setting doesn't work.

I tried to implement SAVi model training and SlotFormer training for the OBJ3D and followed your obj3d.mdinstructions.
I simply copied and pasted the code given in obj3d.md, however failed to train models in multi GPUs.
It did run but only in a single GPU.
(I found out that the extract_slot code runs in multi GPUs.)

Could you give me a hand?

**Comment by Wuziyi616** [comment]
Thanks for your interest in our work, and sorry for the confusion in the instruction. To run multi-GPU DDP training, you need to replace `python` with `python -m torch.distributed.launch --nproc_per_node=$NUM_GPUS --master_port=29501 train.py xxx`, where `$NUM_GPUS` is the number of GPUs you want to use.

Also, I think if the model can be trained on 1 GPU (with the same batch size), then there is no need to do multi-GPU training.
