### ISSUE TITLE
Weird bug about module import

### ISSUE THREAD

**Issue by HaronW** [pairlab/SlotFormer#6]
Hi there,

during evaluating slotformer in video prediction on OBJ3D, I met a weird bug. I built the environment following your instructions in install.md with environment.yml and set up nerv. I even tried it on different computers, and it still raises the same error.

When I run python slotformer/video_prediction/test_vp.py, I get this error:
```
  File ".../SlotFormer/slotformer/video_prediction/vp_utils.py", line 13, in <module>
    from slotformer.base_slots.models import to_rgb_from_tensor
ModuleNotFoundError: No module named 'slotformer'
```
I checked the import of slotformer in your code and it seems correct to me. I tried to type in the same import code in PyCharm and the import of slotformer can be auto-completed.

Could you give me a hand?

**Comment by Wuziyi616** [comment]
Hummm, that's weird. Have you run this step? `No mudule named slotformer` means you haven't installed this repo as a package to your system, so your python interpreter cannot find it.

![image](https://github.com/pairlab/SlotFormer/assets/37072215/00653444-4e31-46eb-9f72-35d4e094a299)

To check if you have installed slotformer, can you try `pip show slotformer`? If it doesn't show anything, then that means you haven't do the `pip install -e .` step. Please do that following the instruction and re-try. Hope this helps!

**Comment by HaronW** [comment]
Thanks for your help. It worked!
